function Get-CUCMDeviceName {
    param(
        [Parameter(Mandatory)][String]$UserIDAssociatedWithDevice
    )

    $AXL = @"
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/9.1">
   <soapenv:Header/>
   <soapenv:Body>
      <ns:executeSQLQuery sequence="?">
        <sql>select device.name, enduser.userid from device, enduser, enduserdevicemap
            where device.pkid=enduserdevicemap.fkdevice and  
            enduser.pkid=enduserdevicemap.fkenduser and enduser.userid = '$UserIDAssociatedWithDevice'
        </sql>
      </ns:executeSQLQuery>
   </soapenv:Body>
</soapenv:Envelope>
"@

    $XmlContent = Invoke-CUCMSOAPAPIFunction -AXL $AXL -MethodName executeSQLQuery

    $XmlContent.Envelope.Body.executeSQLQueryResponse.return.row
}

function Remove-CUCMPhone {
    param(
        [Parameter(Mandatory)][String]$Name
    )

    $AXL = @"
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/9.1">
    <soapenv:Header/>
    <soapenv:Body>
        <ns:removePhone>
        <name>$Name</name>
        </ns:removePhone>
    </soapenv:Body>
</soapenv:Envelope>
"@

    Invoke-CUCMSOAPAPIFunction -AXL $AXL
}


function Invoke-CUCMSOAPAPIFunction {
    param(
        [parameter(Mandatory)]$AXL,
        [parameter(Mandatory)]$MethodName
    )
    
#    add-type @"
#    using System.Net;
#    using System.Security.Cryptography.X509Certificates;
#    public class TrustAllCertsPolicy : ICertificatePolicy {
#        public bool CheckValidationResult(
#            ServicePoint srvPoint, X509Certificate certificate,
#            WebRequest request, int certificateProblem) {
#            return true;
#        }
#    }
#"@
#    [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

    $Credential = Import-Clixml $env:USERPROFILE\CUCMCredential.txt
    #if ($AXLWebSession) {
    #    $Result = Invoke-WebRequest -ContentType "text/xml" -Headers @{"SOAPAction"="CUCM:DB ver=9.1"} -Body $AXL -Uri https://ter-cucm-pub1:8443/axl/ -Method Post -Credential $Credential -WebSession $AXLWebSession
    #} else {
        #$Result = Invoke-WebRequest -ContentType "text/xml;charset=UTF-8" -Headers @{"SOAPAction"="CUCM:DB ver=9.1 $MethodName"} -Body $AXL -Uri https://ter-cucm-pub1:8443/axl/ -Method Post -Credential $Credential -SessionVariable AXLWebSession
        $Result = Invoke-WebRequest -ContentType "text/xml" -Headers @{"SOAPAction"="CUCM:DB ver=9.1"} -Body $AXL -Uri https://ter-cucm-pub1:8443/axl/ -Method Post -Credential $Credential -SessionVariable AXLWebSession
    #}

    $XmlContent = [xml]$Result.Content

    $XmlContent
}

function New-CUCMCredential {
    $CUCMCredential = Get-Credential
    $CUCMCredential | Export-Clixml $env:USERPROFILE\CUCMCredential.txt

}

function get-StuffViaWebServiceProxy {

    $Credential = get-credential

    $CUCMAXL = New-WebServiceProxy -Uri "C:\Users\cmagnuson\Desktop\axlsqltoolkit\schema\current\AXLAPI.wsdl" -Class "CUCMAXL" -Credential $Credential

    #get autogenerated namespace
    $TypeName = $CUCMAXL.GetType().Namespace
    $Type = $CUCMAXL.GetType()
    $GetCssReq = New-Object ($TypeName + '.GetCssReq')
    $GetCssReq|gm

    $String100 = New-Object ($TypeName + '.String100')
    $CUCMAXL.getCss($GetCssReq)
    $CUCMAXL.getCss($true)

    $GetPhoneReq = New-Object ($type + '.GetPhoneReq')


    [Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1kit_schema_current_AXLAPI_wsdl]|gm
    [Reflection.Assembly]::GetAssembly($Type)| select -ExpandProperty definedtypes


    $myFundGooferDt = ($type + '.FundInput')
    $myFundDt = ($type + '.Fund')
    $myInputContextDt = ($type + '.Context') 
    $myFundIdentityDt = ($type + '.FundIdentity') 
    # Create the Objects needed
    $myFundGoofer = new-object ($myFundGooferDt) 
    $myFund = new-object ($myFundDt) 
    $myInputContext = new-object ($myInputContextDt)
    $myFundIdentity = New-Object $myFundIdentityDt
    # Assign values
    $myFundIdentity.Isin="SE9900558666"
    $myFundIdentity.FundBaseCurrencyId="SEK"
    $myInputContext.ExtChannelId="ChannelMan"
    $myInputContext.ExtId="RubberDuck"
    $myInputContext.ExtPosReference="RubberDuck"
    $myInputContext.ExtUser="RubberDuck"
    $myInputContext.LanguageId="809"
    $myFund.Identity=$myFundIdentity

    $myFundGoofer.Fund = $myFund
    $myFundGoofer.InputContext = $myInputContext

    #Tada
    $fundSrvc.Get($myFundGoofer)

}

function get-StuffViaOlderStyle {
    $Credential = get-credential

    $AXL = @"
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/8.5">
  <soapenv:Header/>
  <soapenv:Body>
    <ns:executeSQLQuery>
      <sql>Select name from device where tkclass = 1</sql>
    </ns:executeSQLQuery>
  </soapenv:Body>
</soapenv:Envelope>
"@

    $Result = Invoke-WebRequest -ContentType "text/xml" -Headers @{"SOAPAction"="CUCM:DB ver=8.5"} -Body $AXL -Uri https://ter-cucm-pub1:8443/axl/ -Method Post -Credential $Credential

    $XmlContent = [xml]$Result.Content


    $AXL = @"
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/8.5">
   <soapenv:Header/>
   <soapenv:Body>
      <ns:executeSQLQuery sequence="?">
        <sql>select device.pkid, device.name, enduser.pkid, enduser.userid from device, enduser, enduserdevicemap
            where device.pkid=enduserdevicemap.fkdevice and
            enduser.pkid=enduserdevicemap.fkenduser
        </sql>
      </ns:executeSQLQuery>
   </soapenv:Body>
</soapenv:Envelope>
"@

    $Result = Invoke-WebRequest -ContentType "text/xml" -Headers @{"SOAPAction"="CUCM:DB ver=8.5"} -Body $AXL -Uri https://ter-cucm-pub1:8443/axl/ -Method Post -Credential $Credential

    $XmlContent = [xml]$Result.Content

    Invoke-WebRequest -ContentType "text/xml" -Headers @{"SOAPAction"="CUCM:DB ver=8.5"} -Uri https://ter-cucm-pub1:8443/axl/?WSDL -Method get -Credential $Credential

}